### ISSUE TITLE
Support for text extraction from binary files

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-records-files#53]
Elasticsearch provides a plugin to process binary files via Tika, meaning text extraction. The plugin is [Ingest Attachment Processor](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html).

I have done a dummy test (not tied to Invenio) with an ``.odt`` file with ``Test for ingest attachment pipeline`` as content. The result is:

```python
from elasticsearch_dsl import DocType, Text
from elasticsearch_dsl.connections import connections
import json
import base64

connections.configure(
    default={'hosts': 'localhost:9200', 'timeout': 30}
)


class Binary(DocType):
    data = Text()

    class Meta:
        index = 'test'

    def save(self, **kwargs):
        return super(Binary, self).save(pipeline='attachment', **kwargs)


Binary.init()

with open("/path/to/random/binary/file.odt", "rb") as image_file:
    encoded_string = base64.b64encode(image_file.read())

test = Binary(data=encoded_string)
test.save()
```

Assuming the pipeline has been set (see first link for details). If generates a document similar to:

```json
{
        "_index" : "test",
        "_type" : "binary",
        "_id" : "AWccCjfwxZ0hom_UTBxM",
        "_score" : 1.0,
        "_source" : {
          "data" : "[Encoded b64 string deleted for simplicity]",
          "attachment" : {
            "date" : "2018-11-16T09:19:03.540389798",
            "content_type" : "application/vnd.oasis.opendocument.text",
            "language" : "no",
            "content" : "Test for ingest attachment pipeline",
            "content_length" : 37
          }
        }
      }
    ]
  }
```

The corresponding part should also be done in ``invenio-files-rest``. I am willing to work on this.

**Comment by slint** [comment]
There was already some efforts in the past to make [the integrate the mapper attachments plugin](https://github.com/inveniosoftware/invenio-records-files/blob/db2799f48ba0b1b443812cafdeb4295272053bae/invenio_records_files/receivers.py#L34-L61). I think it worked but wasn't used by anybody on a production service...

**Comment by ppanero** [comment]
@slint Hmm I see... For my service is quite important, not to say mandatory. So I will have to implement it anyway, if you see that it could be useful here I am more than happy to do it. If not I will do it in a custom manner. If it should be here, feel free to assign me the issue :) .

Cheers!

**Comment by miltalex** [comment]
I would like to add, that for E-Publishing is a nice-to-have feature and I will be glad to help.
